language: r
cache: packages
r: bioc-devel
sudo: false
warning_are_errors: false

addons:
  apt:
    packages:
      - libnetcdf-dev
      - libhdf5-dev
      - texlive-fonts-extra
      - xvfb

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
