/* Generated by re2c 3.1 on Tue Sep 12 11:08:00 2023 */

static int _spectrum_re(const char *str, const char ** _start, const char ** _end)
{
	const char *YYCURSOR = str, *YYMARKER;
	const char *start, *end;

	/* Autogenerated tag variables used by the lexer to track tag values. */
	const char *yyt1;


	for(;;) {

{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case ' ': goto yy4;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			yyt1 = YYCURSOR;
			goto yy6;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
	{ return  1; }
yy2:
	++YYCURSOR;
yy3:
	{ return -1; }
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
	{ continue; }
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':': goto yy8;
		default: goto yy3;
	}
yy7:
	yych = *++YYCURSOR;
yy8:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy7;
		case ':': goto yy10;
		default: goto yy9;
	}
yy9:
	YYCURSOR = YYMARKER;
	goto yy3;
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy9;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy13;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy12;
	}
yy12:
	start = yyt1;
	end = YYCURSOR;
	{
			* _start = start;
			* _end = end;
			return 0;
		}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy13;
		default: goto yy12;
	}
}

	}
}

/* vim: set filetype=c: */
