#' Extract peak data from a RI file
#'
#' A convenient function to extract peak data from a RI file. This function is mostly
#' intended for debugging purposes, for example, when a given peak is not found within
#' a expected time range (which could be because a faulty retention time correction).
#' The arguments of this function are similar as those of the [ncdf4_data_extract()] function.
#'
#' The function takes a RI file generated by "TargetSearch" (binary or text works)
#' and extracts all the peaks detected of given _m/z_ ion traces in a given time range.
#' The time range can be in seconds or arbitrary retention time index units.
#'
#' The output is simply a four column matrix in which a row is a peak of a given ion
#' trace at a retention time (index). The output is always a matrix even if no peaks
#' are found, in which case the number of rows is zero.
#'
#' @param RIfile A path to a RI file format (binary or text).
#' @param massValues A numeric vector representing m/z values. The values will be converted
#'   to integers internally.
#' @param timeRange A numeric vector of length 2 representing the lower and upper
#'   time limits.
#' @param useRT Logical. If `TRUE`, the time range is in seconds, otherwise if `FALSE`
#'   (default), the time range is inretention time index units (`TRUE`).
#' @param ... extra parameters passed to internal functions. This should be needed.
#'   However, The most important is `columns` which is used for text-format RI files.
#'   See [text2bin()].
#'
#' @return
#' A four column matrix with columm names described below. Each row represents a peak
#' in the specified time range. Potentially, there could be zero rows.
#'
#' * `RI` retention time index of the peak.
#' * `RT` retention time.
#' * `Intensity` peak height intensity
#' * `mz` the _m/z_ of the peak
#'
#' @note
#' This function is intended to be used internally or by advances users. It can be used
#' for debugging when `TargetSearch` fails to find a peak.
#'
#' @seealso [text2bin()], [ncdf4_data_extract()]
#' @export
#' @md
#' @author Alvaro Cuadros-Inostroza
#' @examples
#' require(TargetSearchData)
#' path <- file.path(find.package("TargetSearchData"), "gc-ms-data")
#' rifile <- dir(path, pattern="RI_", full=TRUE)[1]
#'
#' # extract peak data for m/z 116 and 117 in time range 180 - 220 seconds
#' data <- ri_data_extract(rifile, c(116, 117), c(180, 220), useRT=TRUE)
#'
#' # same but using Retention Time Index
#' data <- ri_data_extract(rifile, c(116, 117), c(205000, 228000), useRT=FALSE)
#'
`ri_data_extract` <- function(RIfile, massValues, timeRange, useRT=FALSE, ...)
{
    assert_that(is.numeric(timeRange), length(timeRange) == 2)
    assert_that(is.numeric(massValues))
    ref <- cbind(minRI=timeRange[1], mz=massValues, maxRI=timeRange[2])
    result <- getAllPeaks(RIfile, ref, useRT, ...)
    result <- result[, c('RI', 'RT', 'Int', 'mz'), drop=FALSE]
    colnames(result)[3] <- 'Intensity'
    result
}

# vim: set ts=4 sw=4 et:
